# Generated by Django 2.0.3 on 2018-03-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0002_auto_20180320_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_complement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_variation',
            field=models.BooleanField(default=False),
        ),
    ]
