# Generated by Django 2.0.3 on 2018-03-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0005_auto_20180322_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
